### ISSUE TITLE
Error in MetaTrader 5 Version 5.00 build 2885 - 14 April 2021

### ISSUE THREAD

**Issue by wedersonrsouza** [ejtraderLabs/Metatrader5-Docker#2]
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 299 (char 298)

**Comment by traderpedroso** [comment]
> json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 299 (char 298)

has been fixed and update to last verstion
