### ISSUE TITLE
Docker e uso da API do Metatrader

### ISSUE THREAD

**Issue by michelmetran** [ejtraderLabs/Metatrader5-Docker#3]
Sou usuário de linux e vi no projeto a possibilidade de rodar a interface do MT5, usando Wine, em um docker. Sucesso!
Além disso, com o [ejtraderMT](https://github.com/ejtraderLabs/ejtraderMT) consegui obter e manipular dados e ordens!

Contudo,  gostaria de saber se existe alguma maneira de usar a API oficial do Metatrader nesse container/docker que foi disponibilizado?!
- https://pypi.org/project/MetaTrader5/
- https://www.mql5.com/pt/docs/integration/python_metatrader5

Ao tentar instalar, dá erro, visto que estou no sistema linux. Ao tentar dar o comando `pip3 install MetaTrader5` recebo o seguinte erro:

> ERROR: Could not find a version that satisfies the requirement MetaTrader5 (from versions: none)
> ERROR: No matching distribution found for MetaTrader5

... gostaria de reaproveitar códigos que já fiz e estudei com a API oficial.

**Comment by traderpedroso** [comment]
> Sou usuário de linux e vi no projeto a possibilidade de rodar a interface do MT5, usando Wine, em um docker. Sucesso! Além disso, com o [ejtraderMT](https://github.com/ejtraderLabs/ejtraderMT) consegui obter e manipular dados e ordens!
> 
> Contudo, gostaria de saber se existe alguma maneira de usar a API oficial do Metatrader nesse container/docker que foi disponibilizado?!
> 
> * https://pypi.org/project/MetaTrader5/
> * https://www.mql5.com/pt/docs/integration/python_metatrader5
> 
> Ao tentar instalar, dá erro, visto que estou no sistema linux. Ao tentar dar o comando `pip3 install MetaTrader5` recebo o seguinte erro:
> 
> > ERROR: Could not find a version that satisfies the requirement MetaTrader5 (from versions: none)
> > ERROR: No matching distribution found for MetaTrader5
> 
> ... gostaria de reaproveitar códigos que já fiz e estudei com a API oficial.

Não Linux não é possível mesmo usando python.exe no wine gera alguns erros porque api oficial somente via windows infelizmente
