### ISSUE TITLE
Does anyone still able to use this docker?

### ISSUE THREAD

**Issue by seankcw** [ejtraderLabs/Metatrader5-Docker#5]
There are some errors in terminal and I cannot use/compile any MT5's EAs.

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/3282095/233880370-c736a21c-112e-44a1-b620-7db7a013f8cb.png">

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/3282095/233880533-4df42aff-9905-4de4-9888-2160262c63a4.png">

**Comment by ethanopp** [comment]
I've tried installing on linux docker as well as windows docker and getting same issue on both - were you ever able to figure this out @seankcw? @ejtraderPlugins perhaps you could shed some light?

**Comment by traderpedroso** [comment]
well I'll check it and compile again I guess its some thing to do new version of MT5 missing samba-winbind
