### ISSUE TITLE
Metatrader needs and update

### ISSUE THREAD

**Issue by DiMiTriFrog** [ejtraderLabs/Metatrader5-Docker#6]
I posted a issue some weeks ago because the ejtrader let work for myself. Seems icmarkets-demo need a new version of Metatrader and the version installed on Docker it's old. 
Could you update it ?

<img width="669" alt="Screenshot 2023-09-22 at 09 15 47" src="https://github.com/ejtraderLabs/Metatrader5-Docker/assets/38754548/5368543e-c872-4589-8fbd-98bc689ea00e">

**Comment by traderpedroso** [comment]
clone the code and add new metatrader folder run with /portable to create a full folder
